dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation'

    implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.51.3.0'
    implementation group: 'software.amazon.awssdk', name: 's3', version: '2.26.15'

    implementation project(':loa-library:loa-file-service')
    implementation project(':loa-library:loa-stage-service')
    implementation project(':loa-library:loa-number-service')
    implementation project(':loa-library:loa-document-service')
    implementation project(':loa-library:loa-staging-client-service')

}
