package com.github.bottomlessarchive.loa.application.domain;

public enum ApplicationType {

    ADMINISTRATOR_APPLICATION,
    CONDUCTOR_APPLICATION,
    DOWNLOADER_APPLICATION,
    GENERATOR_APPLICATION,
    INDEXER_APPLICATION,
    QUEUE_APPLICATION,
    VAULT_APPLICATION,
    WEB_APPLICATION
}
