= Staging Application

This application is responsible for holding documents before they are being moved to their final place in one of the <<Vault Application>> instances.

== Workflow

The <<Staging Application>> is a very simple webserver that has three endpoints.

A https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST[POST] endpoint stores documents on the staging location.

A https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET[GET] endpoint return the stored document on the staging location and removes it from the stage.

A https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE[DELETE] endpoint removes the stored document from the staging location. This endpoint is only used when the <<Vault Application>> determines that the document is a duplicate based on its checksum, filesize and type. In this case, downloading the document is not needed, it can safely be removed.

.Parameters
|===
| Parameter | Description

| **loa.staging.path**
| Where should the <<Staging Application>> put the files it acquires for staging.
|===
