= Installing Elasticsearch

Elasticsearch is only necessary for indexing! If you only want to collect the PDF documents then it's unnecessary for you!

You can download Elasticsearch 8.3.1 https://www.elastic.co/downloads/past-releases/elasticsearch-8-3-1[here].

After the download complete unzip it. You also need to do some slight adjustments to the default configuration.

Go to the elasticsearch/config folder. Open the jvm.options file in the text editor and edit the following parameters to adjust the memory. We suggest setting at least 4 GB of memory for Elasticsearch. Even if you don't have a lot of files.

....
-Xms1g
-Xmx1g
....

For example:

....
-Xms4g
-Xmx4g
....

If you want to change the data directory then open the config/elasticsearch.yml file, uncomment the path.data and write the expected data path to it.

For example:

....
path.data: C:\loa\indexer\data
....

After this is done you are ready to run Elasticsearch by going into the elasticsearch folder and writing `.\bin\elasticsearch` to the console.
